version: '3,7'

services:
  postgres:
    image: 'bitnami/postgresql:latest'
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_PASSWORD=docker
      - POSTGRES_USER=docker
      - POSTGRES_DB=cash-io
    # volumes:
    #   - 'cash_io_pg_data:/bitnami/postgresql'

# volumes:
#   cash_io_pg_data: